#!/bin/sh
if
[ -f /tmp/google.tmp ]
then
rm -rf /tmp/google.tmp
fi
echo
echo "Google DNS Passive Fingerprinter v0.1"
echo "-------------------------------------"
echo
echo -n "Enter base domain, exluding www [foo.com]: "
read SITE
echo -n "How many pages would you like to search?: "
read NUM
echo

echo "Finding subdomains for the site $SITE"

lynx -dump "http://www.google.com/search?q=site:$SITE+-www.$SITE&num=$NUM" | sed -n 's/\. http:\/\/[[:alpha:]]*.sun.com\//& /p' | awk '{print $2}' | sed 's/http:\/\///' | sed -s 's/\///' | sort -u > /tmp/google.tmp
for each in $(cat /tmp/google.tmp)
do host $each
sleep 1
done
